import streamlit as st
import pandas as pd
import numpy as np


# =========================================================
# PAGE CONFIG
# =========================================================

st.set_page_config(
    page_title="GramVyapar AI",
    page_icon="🌱",
    layout="wide",
    initial_sidebar_state="collapsed",
)


# =========================================================
# COLOURS
# =========================================================

OLIVE = "#526A3A"
GREEN = "#7D9A55"
ORANGE = "#C88A3D"
CREAM = "#FAF8F1"
BROWN = "#33352C"
WHITE = "#FFFFFF"
LIGHT_GREY = "#F0F1ED"


# =========================================================
# SESSION STATE
# =========================================================

if "page" not in st.session_state:
    st.session_state.page = 1

if "skills" not in st.session_state:
    st.session_state.skills = []

if "experience" not in st.session_state:
    st.session_state.experience = 0

if "capital" not in st.session_state:
    st.session_state.capital = 50000

if "interests" not in st.session_state:
    st.session_state.interests = []

if "risk" not in st.session_state:
    st.session_state.risk = "Medium"

if "existing_business" not in st.session_state:
    st.session_state.existing_business = False

if "business_name" not in st.session_state:
    st.session_state.business_name = ""

if "language" not in st.session_state:
    st.session_state.language = "English"


# =========================================================
# GLOBAL CSS
# IMPORTANT:
# This CSS only styles Streamlit widgets.
# No HTML is generated by the application.
# =========================================================

st.markdown(
    f"""
    <style>

    .stApp {{
        background-color: {CREAM};
        color: {BROWN};
    }}

    [data-testid="stHeader"] {{
        background-color: {CREAM};
    }}

    .block-container {{
        padding-top: 2rem;
        padding-bottom: 3rem;
        max-width: 1350px;
    }}

    h1, h2, h3, h4 {{
        color: {BROWN};
    }}

    p, label {{
        color: {BROWN};
    }}

    /* Primary buttons */

    div.stButton > button {{
        background-color: {OLIVE};
        color: white;
        border: 1px solid {OLIVE};
        border-radius: 10px;
        min-height: 44px;
        font-weight: 600;
    }}

    div.stButton > button:hover {{
        background-color: {GREEN};
        color: white;
        border-color: {GREEN};
    }}

    /* Secondary buttons */

    div.stButton > button[kind="secondary"] {{
        background-color: white;
        color: {OLIVE};
        border: 1px solid #B8BDB2;
    }}

    /* Inputs */

    div[data-baseweb="select"] > div {{
        background-color: white;
        color: {BROWN};
    }}

    div[data-baseweb="select"] span {{
        color: {BROWN};
    }}

    input {{
        color: {BROWN} !important;
    }}

    textarea {{
        color: {BROWN} !important;
    }}

    /* Slider */

    div[data-testid="stSlider"] {{
        padding-top: 5px;
    }}

    /* Checkbox */

    div[data-testid="stCheckbox"] {{
        background-color: {LIGHT_GREY};
        border: 2px solid #B8BDB2;
        border-radius: 10px;
        padding: 10px 14px;
    }}

    /* Radio */

    div[data-testid="stRadio"] label {{
        color: {BROWN};
    }}

    /* Metrics */

    div[data-testid="stMetric"] {{
        background-color: white;
        border: 1px solid #E1E2DC;
        border-radius: 12px;
        padding: 15px;
    }}

    /* Alerts */

    div[data-testid="stAlert"] {{
        border-radius: 10px;
    }}

    </style>
    """,
    unsafe_allow_html=True,
)


# =========================================================
# HEADER
# =========================================================

def render_header():

    col1, col2 = st.columns([3, 1])

    with col1:
        st.title("🌱 GramVyapar AI")
        st.caption("Know Before You Borrow.")

    with col2:
        language = st.selectbox(
            "Language",
            ["English", "Malayalam"],
            index=0 if st.session_state.language == "English" else 1,
            key="language_selector",
        )

        st.session_state.language = language


# =========================================================
# FRAME 1 — PROFILE INPUT
# =========================================================

def render_frame_1():

    st.subheader("Step 1 of 10")
    st.title("Tell us about yourself")
    st.write(
        "We'll use your skills, experience, capital and interests "
        "to identify suitable local business opportunities."
    )

    st.divider()

    # -----------------------------------------------------
    # SKILLS
    # -----------------------------------------------------

    st.subheader("🛠️ Your skills")

    skill_options = [
        "Cooking",
        "Tailoring",
        "Farming",
        "Dairy",
        "Handicrafts",
        "Food Processing",
        "Sales",
        "Repair & Maintenance",
        "Digital Skills",
        "Driving",
    ]

    skills = st.multiselect(
        "Select your skills",
        skill_options,
        default=st.session_state.skills,
        key="skills_input",
    )

    custom_skill = st.text_input(
        "Other skill (optional)",
        placeholder="Type another skill...",
        key="custom_skill",
    )

    if custom_skill.strip():
        if custom_skill.strip() not in skills:
            skills = skills + [custom_skill.strip()]

    st.session_state.skills = skills

    # -----------------------------------------------------
    # EXPERIENCE
    # -----------------------------------------------------

    st.subheader("📈 Experience")

    experience = st.number_input(
        "Years of relevant experience",
        min_value=0,
        max_value=50,
        value=int(st.session_state.experience),
        step=1,
        key="experience_input",
    )

    st.session_state.experience = experience

    # -----------------------------------------------------
    # CAPITAL
    # -----------------------------------------------------

    st.subheader("💰 Available capital")

    capital = st.slider(
        "How much own capital can you invest?",
        min_value=0,
        max_value=500000,
        value=int(st.session_state.capital),
        step=5000,
        format="₹%d",
        key="capital_input",
    )

    st.session_state.capital = capital

    st.info(
        f"Own capital available: ₹{capital:,.0f}"
    )

    # -----------------------------------------------------
    # INTERESTS
    # -----------------------------------------------------

    st.subheader("🎯 Business interests")

    interest_options = [
        "Food & Bakery",
        "Dairy",
        "Tailoring",
        "Retail",
        "Agriculture",
        "Food Processing",
        "Services",
        "Handicrafts",
        "Small Manufacturing",
    ]

    interests = st.multiselect(
        "What type of business interests you?",
        interest_options,
        default=st.session_state.interests,
        key="interests_input",
    )

    custom_interest = st.text_input(
        "Other interest (optional)",
        placeholder="Type another business interest...",
        key="custom_interest",
    )

    if custom_interest.strip():
        if custom_interest.strip() not in interests:
            interests = interests + [custom_interest.strip()]

    st.session_state.interests = interests

    # -----------------------------------------------------
    # RISK
    # -----------------------------------------------------

    st.subheader("⚖️ Risk preference")

    risk = st.radio(
        "How much business risk are you comfortable with?",
        ["Low", "Medium", "High"],
        index=["Low", "Medium", "High"].index(
            st.session_state.risk
        ),
        horizontal=True,
        key="risk_input",
    )

    st.session_state.risk = risk

    # -----------------------------------------------------
    # EXISTING BUSINESS
    # -----------------------------------------------------

    st.subheader("🏪 Existing business")

    existing = st.checkbox(
        "I already have a business",
        value=st.session_state.existing_business,
        key="existing_business_input",
    )

    st.session_state.existing_business = existing

    if existing:

        business_name = st.text_input(
            "Business name",
            value=st.session_state.business_name,
            placeholder="Enter your business name",
            key="business_name_input",
        )

        st.session_state.business_name = business_name

    # -----------------------------------------------------
    # CONTINUE
    # -----------------------------------------------------

    st.divider()

    col1, col2, col3 = st.columns([1, 2, 1])

    with col2:

        if st.button(
            "Continue →",
            use_container_width=True,
            type="primary",
        ):
            st.session_state.page = 2
            st.rerun()


# =========================================================
# FRAME 2 — LOCAL DASHBOARD
# NO CUSTOM HTML
# =========================================================

def render_frame_2():

    st.subheader("Step 2 of 10")
    st.title("📍 Your Local Market")

    st.write(
        "Let's understand the local market before recommending a business."
    )

    st.divider()

    # -----------------------------------------------------
    # LOCATION
    # -----------------------------------------------------

    st.subheader("Choose your location")

    col1, col2, col3 = st.columns(3)

    with col1:

        district = st.selectbox(
            "District",
            [
                "Ernakulam",
                "Kozhikode",
                "Thrissur",
                "Malappuram",
                "Kollam",
            ],
            index=0,
        )

    with col2:

        local_body = st.selectbox(
            "Local Body",
            [
                "Sample Panchayat",
                "Municipality",
                "Corporation",
            ],
        )

    with col3:

        ward = st.selectbox(
            "Ward",
            [
                "Ward 1",
                "Ward 2",
                "Ward 3",
                "Ward 4",
                "Ward 5",
            ],
        )

    st.caption(
        "📌 Demo location data is being used for this prototype."
    )

    # -----------------------------------------------------
    # DATA COVERAGE
    # -----------------------------------------------------

    st.subheader("Data coverage")

    coverage_col1, coverage_col2 = st.columns([3, 1])

    with coverage_col1:

        st.info(
            "Current analysis level: **District-level fallback**"
        )

    with coverage_col2:

        st.metric(
            "Confidence",
            "Medium",
        )

    # -----------------------------------------------------
    # LOCAL MARKET METRICS
    # -----------------------------------------------------

    st.subheader("Local market snapshot")

    m1, m2, m3, m4 = st.columns(4)

    with m1:
        st.metric(
            "Business Density",
            "42 / km²",
            "Demo",
        )

    with m2:
        st.metric(
            "Population",
            "18,420",
            "2011 Census",
        )

    with m3:
        st.metric(
            "Seasonal Demand",
            "Medium",
            "Estimated",
        )

    with m4:
        st.metric(
            "Resource Availability",
            "Good",
            "Estimated",
        )

    st.caption(
        "Each value should be replaced with verified local data in the production version."
    )

    # -----------------------------------------------------
    # MAP
    # -----------------------------------------------------

    st.subheader("Local market area")

    # Small demo map.
    # Later this can be replaced with actual village/ward coordinates.

    map_data = pd.DataFrame(
        {
            "lat": [10.0159, 10.0200, 10.0100],
            "lon": [76.3419, 76.3500, 76.3350],
        }
    )

    st.map(
        map_data,
        latitude="lat",
        longitude="lon",
        zoom=11,
    )

    st.caption(
        "Map points are illustrative only. Connect verified local business/location data later."
    )

    # -----------------------------------------------------
    # MARKET SIGNALS
    # -----------------------------------------------------

    st.subheader("Market signals")

    signal_col1, signal_col2 = st.columns(2)

    with signal_col1:

        with st.container(border=True):

            st.markdown("### 📈 Demand signal")

            st.write(
                "Local demand appears **moderate** for essential household "
                "and food-related services."
            )

            st.caption(
                "Source status: Estimate"
            )

    with signal_col2:

        with st.container(border=True):

            st.markdown("### 🏪 Competition signal")

            st.write(
                "Competition appears **moderate**. More detailed competitor "
                "mapping will improve confidence."
            )

            st.caption(
                "Source status: Estimate"
            )

    # -----------------------------------------------------
    # MARKET REACH
    # -----------------------------------------------------

    st.subheader("Recommended market reach")

    reach_col1, reach_col2, reach_col3 = st.columns(3)

    with reach_col1:

        with st.container(border=True):

            st.metric(
                "Primary Reach",
                "0–5 km",
            )

            st.caption(
                "Immediate local customers"
            )

    with reach_col2:

        with st.container(border=True):

            st.metric(
                "Extended Reach",
                "5–10 km",
            )

            st.caption(
                "Nearby villages / markets"
            )

    with reach_col3:

        with st.container(border=True):

            st.metric(
                "Analysis Radius",
                "10 km",
            )

            st.caption(
                "Prototype target radius"
            )

    # -----------------------------------------------------
    # NAVIGATION
    # -----------------------------------------------------

    st.divider()

    back_col, empty_col, next_col = st.columns([1, 2, 1])

    with back_col:

        if st.button(
            "← Back",
            use_container_width=True,
        ):
            st.session_state.page = 1
            st.rerun()

    with next_col:

        if st.button(
            "Continue →",
            use_container_width=True,
            type="primary",
        ):
            st.session_state.page = 3
            st.rerun()


# =========================================================
# FRAME 3 — PLACEHOLDER
# =========================================================

def render_frame_3():

    st.subheader("Step 3 of 10")
    st.title("🎯 Opportunity Radar")

    st.info(
        "Frame 3 will rank business opportunities using "
        "Demand, Competition, Skills, Capital and Risk."
    )

    st.divider()

    st.subheader("Coming next")

    col1, col2, col3 = st.columns(3)

    with col1:

        with st.container(border=True):

            st.metric(
                "Demand",
                "High",
            )

            st.write(
                "Estimated local customer demand."
            )

    with col2:

        with st.container(border=True):

            st.metric(
                "Competition",
                "Medium",
            )

            st.write(
                "Number and strength of nearby competitors."
            )

    with col3:

        with st.container(border=True):

            st.metric(
                "Capital Fit",
                "Good",
            )

            st.write(
                "Fit with the user's available capital."
            )

    st.divider()

    if st.button("← Back to Local Dashboard"):
        st.session_state.page = 2
        st.rerun()


# =========================================================
# MAIN APP
# =========================================================

render_header()

st.divider()

if st.session_state.page == 1:

    render_frame_1()

elif st.session_state.page == 2:

    render_frame_2()

elif st.session_state.page == 3:

    render_frame_3()
